<?php

namespace App\Helpers\Interfaces;

/**
 * App\Helpers\Interfaces\Time.
 * 
 * Defines time constants globally.
 */
interface Time
{
    /**
     * TimeIntervals in seconds.
     * 
     * @var int
     */
    const ONE_HOUR_IN_SECONDS = 3600;
    const ONE_DAY_IN_SECONDS = 86400;
    const TWO_DAYS_IN_SECONDS = 172800;
    const ONE_WEEK_IN_SECONDS = 604800;

    const INTERVALS = ['0:00', '0:30', '1:00', '1:30', '2:00', '2:30', '3:00', '3:30', '4:00', '4:30', '5:00', '5:30', '6:00', '6:30', '7:00', '7:30', '8:00', '8:30', '9:00', '9:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30', '22:00', '22:30', '23:00', '23:30'];

    const DURATION = [
        'HOURS' => [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        'MINUTES' => [0, 15, 30, 45]
    ];

    const TIMEZONES = [
        ['timezone' => 'Pacific/Midway', 'label' => '(GMT-11:00) Midway Island, Samoa'],
        ['timezone' => 'Pacific/Pago_Pago', 'label' => '(GMT-11:00) Pago Pago'],
        ['timezone' => 'Pacific/Honolulu', 'label' => '(GMT-10:00) Hawaii'],
        ['timezone' => 'America/Anchorage', 'label' => '(GMT-8:00) Alaska'],
        ['timezone' => 'America/Juneau', 'label' => '(GMT-8:00) Juneau'],
        ['timezone' => 'America/Vancouver', 'label' => '(GMT-7:00) Vancouver'],
        ['timezone' => 'America/Los_Angeles', 'label' => '(GMT-7:00) Pacific Time (US and Canada)'],
        ['timezone' => 'America/Tijuana', 'label' => '(GMT-7:00) Tijuana'],
        ['timezone' => 'America/Phoenix', 'label' => '(GMT-7:00) Arizona'],
        ['timezone' => 'America/Edmonton', 'label' => '(GMT-6:00) Edmonton'],
        ['timezone' => 'America/Denver', 'label' => '(GMT-6:00) Mountain Time (US and Canada)'],
        ['timezone' => 'America/Mazatlan', 'label' => '(GMT-6:00) Mazatlan'],
        ['timezone' => 'America/Regina', 'label' => '(GMT-6:00) Saskatchewan'],
        ['timezone' => 'America/Guatemala', 'label' => '(GMT-6:00) Guatemala'],
        ['timezone' => 'America/El_Salvador', 'label' => '(GMT-6:00) El Salvador'],
        ['timezone' => 'America/Managua', 'label' => '(GMT-6:00) Managua'],
        ['timezone' => 'America/Costa_Rica', 'label' => '(GMT-6:00) Costa Rica'],
        ['timezone' => 'America/Tegucigalpa', 'label' => '(GMT-6:00) Tegucigalpa'],
        ['timezone' => 'America/Chihuahua', 'label' => '(GMT-6:00) Chihuahua'],
        ['timezone' => 'America/Winnipeg', 'label' => '(GMT-5:00) Winnipeg'],
        ['timezone' => 'America/Chicago', 'label' => '(GMT-5:00) Central Time (US and Canada)'],
        ['timezone' => 'America/Mexico_City', 'label' => '(GMT-5:00) Mexico City'],
        ['timezone' => 'America/Panama', 'label' => '(GMT-5:00) Panama'],
        ['timezone' => 'America/Bogota', 'label' => '(GMT-5:00) Bogota'],
        ['timezone' => 'America/Lima', 'label' => '(GMT-5:00) Lima'],
        ['timezone' => 'America/Monterrey', 'label' => '(GMT-5:00) Monterrey'],
        ['timezone' => 'America/Montreal', 'label' => '(GMT-4:00) Montreal'],
        ['timezone' => 'America/New_York', 'label' => '(GMT-4:00) Eastern Time (US and Canada)'],
        ['timezone' => 'America/Indianapolis', 'label' => '(GMT-4:00) Indiana (East)'],
        ['timezone' => 'America/Puerto_Rico', 'label' => '(GMT-4:00) Puerto Rico'],
        ['timezone' => 'America/Caracas', 'label' => '(GMT-4:00) Caracas'],
        ['timezone' => 'America/Santiago', 'label' => '(GMT-4:00) Santiago'],
        ['timezone' => 'America/La_Paz', 'label' => '(GMT-4:00) La Paz'],
        ['timezone' => 'America/Guyana', 'label' => '(GMT-4:00) Guyana'],
        ['timezone' => 'America/Halifax', 'label' => '(GMT-3:00) Halifax'],
        ['timezone' => 'America/Montevideo', 'label' => '(GMT-3:00) Montevideo'],
        ['timezone' => 'America/Araguaina', 'label' => '(GMT-3:00) Recife'],
        ['timezone' => 'America/Argentina/Buenos_Aires', 'label' => '(GMT-3:00) Buenos Aires, Georgetown'],
        ['timezone' => 'America/Sao_Paulo', 'label' => '(GMT-3:00) Sao Paulo'],
        ['timezone' => 'Canada/Atlantic', 'label' => '(GMT-3:00) Atlantic Time (Canada)'],
        ['timezone' => 'America/St_Johns', 'label' => '(GMT-2:30) Newfoundland and Labrador'],
        ['timezone' => 'America/Godthab', 'label' => '(GMT-2:00) Greenland'],
        ['timezone' => 'Atlantic/Cape_Verde', 'label' => '(GMT-1:00) Cape Verde Islands'],
        ['timezone' => 'Atlantic/Azores', 'label' => '(GMT+0:00) Azores'],
        ['timezone' => 'UTC', 'label' => '(GMT+0:00) Universal Time UTC'],
        ['timezone' => 'Etc/Greenwich', 'label' => '(GMT+0:00) Greenwich Mean Time'],
        ['timezone' => 'Atlantic/Reykjavik', 'label' => '(GMT+0:00) Reykjavik'],
        ['timezone' => 'Africa/Nouakchott', 'label' => '(GMT+0:00) Nouakchott'],
        ['timezone' => 'Europe/Dublin', 'label' => '(GMT+1:00) Dublin'],
        ['timezone' => 'Europe/London', 'label' => '(GMT+1:00) London'],
        ['timezone' => 'Europe/Lisbon', 'label' => '(GMT+1:00) Lisbon'],
        ['timezone' => 'Africa/Casablanca', 'label' => '(GMT+1:00) Casablanca'],
        ['timezone' => 'Africa/Bangui', 'label' => '(GMT+1:00) West Central Africa'],
        ['timezone' => 'Africa/Algiers', 'label' => '(GMT+1:00) Algiers'],
        ['timezone' => 'Africa/Tunis', 'label' => '(GMT+1:00) Tunis'],
        ['timezone' => 'Europe/Belgrade', 'label' => '(GMT+2:00) Belgrade, Bratislava, Ljubljana'],
        ['timezone' => 'CET', 'label' => '(GMT+2:00) Sarajevo, Skopje, Zagreb'],
        ['timezone' => 'Europe/Oslo', 'label' => '(GMT+2:00) Oslo'],
        ['timezone' => 'Europe/Copenhagen', 'label' => '(GMT+2:00) Copenhagen'],
        ['timezone' => 'Europe/Brussels', 'label' => '(GMT+2:00) Brussels'],
        ['timezone' => 'Europe/Berlin', 'label' => '(GMT+2:00) Amsterdam, Berlin, Rome, Stockholm, Vienna'],
        ['timezone' => 'Europe/Amsterdam', 'label' => '(GMT+2:00) Amsterdam'],
        ['timezone' => 'Europe/Rome', 'label' => '(GMT+2:00) Rome'],
        ['timezone' => 'Europe/Stockholm', 'label' => '(GMT+2:00) Stockholm'],
        ['timezone' => 'Europe/Vienna', 'label' => '(GMT+2:00) Vienna'],
        ['timezone' => 'Europe/Luxembourg', 'label' => '(GMT+2:00) Luxembourg'],
        ['timezone' => 'Europe/Paris', 'label' => '(GMT+2:00) Paris'],
        ['timezone' => 'Europe/Zurich', 'label' => '(GMT+2:00) Zurich'],
        ['timezone' => 'Europe/Madrid', 'label' => '(GMT+2:00) Madrid'],
        ['timezone' => 'Africa/Harare', 'label' => '(GMT+2:00) Harare, Pretoria'],
        ['timezone' => 'Europe/Warsaw', 'label' => '(GMT+2:00) Warsaw'],
        ['timezone' => 'Europe/Prague', 'label' => '(GMT+2:00) Prague Bratislava'],
        ['timezone' => 'Europe/Budapest', 'label' => '(GMT+2:00) Budapest'],
        ['timezone' => 'Africa/Tripoli', 'label' => '(GMT+2:00) Tripoli'],
        ['timezone' => 'Africa/Cairo', 'label' => '(GMT+2:00) Cairo'],
        ['timezone' => 'Africa/Johannesburg', 'label' => '(GMT+2:00) Johannesburg'],
        ['timezone' => 'Africa/Khartoum', 'label' => '(GMT+2:00) Khartoum'],
        ['timezone' => 'Europe/Helsinki', 'label' => '(GMT+3:00) Helsinki'],
        ['timezone' => 'Africa/Nairobi', 'label' => '(GMT+3:00) Nairobi'],
        ['timezone' => 'Europe/Sofia', 'label' => '(GMT+3:00) Sofia'],
        ['timezone' => 'Europe/Istanbul', 'label' => '(GMT+3:00) Istanbul'],
        ['timezone' => 'Europe/Athens', 'label' => '(GMT+3:00) Athens'],
        ['timezone' => 'Europe/Bucharest', 'label' => '(GMT+3:00) Bucharest'],
        ['timezone' => 'Asia/Nicosia', 'label' => '(GMT+3:00) Nicosia'],
        ['timezone' => 'Asia/Beirut', 'label' => '(GMT+3:00) Beirut'],
        ['timezone' => 'Asia/Damascus', 'label' => '(GMT+3:00) Damascus'],
        ['timezone' => 'Asia/Jerusalem', 'label' => '(GMT+3:00) Jerusalem'],
        ['timezone' => 'Asia/Amman', 'label' => '(GMT+3:00) Amman'],
        ['timezone' => 'Europe/Moscow', 'label' => '(GMT+3:00) Moscow'],
        ['timezone' => 'Asia/Baghdad', 'label' => '(GMT+3:00) Baghdad'],
        ['timezone' => 'Asia/Kuwait', 'label' => '(GMT+3:00) Kuwait'],
        ['timezone' => 'Asia/Riyadh', 'label' => '(GMT+3:00) Riyadh'],
        ['timezone' => 'Asia/Bahrain', 'label' => '(GMT+3:00) Bahrain'],
        ['timezone' => 'Asia/Qatar', 'label' => '(GMT+3:00) Qatar'],
        ['timezone' => 'Asia/Aden', 'label' => '(GMT+3:00) Aden'],
        ['timezone' => 'Africa/Djibouti', 'label' => '(GMT+3:00) Djibouti'],
        ['timezone' => 'Africa/Mogadishu', 'label' => '(GMT+3:00) Mogadishu'],
        ['timezone' => 'Europe/Kiev', 'label' => '(GMT+3:00) Kiev'],
        ['timezone' => 'Europe/Minsk', 'label' => '(GMT+3:00) Minsk'],
        ['timezone' => 'Asia/Dubai', 'label' => '(GMT+4:00) Dubai'],
        ['timezone' => 'Asia/Muscat', 'label' => '(GMT+4:00) Muscat'],
        ['timezone' => 'Asia/Baku', 'label' => '(GMT+4:00) Baku, Tbilisi, Yerevan'],
        ['timezone' => 'Asia/Tehran', 'label' => '(GMT+4:30) Tehran'],
        ['timezone' => 'Asia/Kabul', 'label' => '(GMT+4:30) Kabul'],
        ['timezone' => 'Asia/Yekaterinburg', 'label' => '(GMT+5:00) Yekaterinburg'],
        ['timezone' => 'Asia/Tashkent', 'label' => '(GMT+5:00) Islamabad, Karachi, Tashkent'],
        ['timezone' => 'Asia/Calcutta', 'label' => '(GMT+5:30) India'],
        ['timezone' => 'Asia/Kolkata', 'label' => '(GMT+5:30) Mumbai, Kolkata, New Delhi'],
        ['timezone' => 'Asia/Colombo', 'label' => '(GMT+5:30) Asia/Colombo'],
        ['timezone' => 'Asia/Kathmandu', 'label' => '(GMT+5:45) Kathmandu'],
        ['timezone' => 'Asia/Almaty', 'label' => '(GMT+6:00) Almaty'],
        ['timezone' => 'Asia/Dacca', 'label' => '(GMT+6:00) Dacca'],
        ['timezone' => 'Asia/Dhaka', 'label' => '(GMT+6:00) Astana, Dhaka'],
        ['timezone' => 'Asia/Rangoon', 'label' => '(GMT+6:30) Rangoon'],
        ['timezone' => 'Asia/Novosibirsk', 'label' => '(GMT+7:00) Novosibirsk'],
        ['timezone' => 'Asia/Krasnoyarsk', 'label' => '(GMT+7:00) Krasnoyarsk'],
        ['timezone' => 'Asia/Bangkok', 'label' => '(GMT+7:00) Bangkok'],
        ['timezone' => 'Asia/Saigon', 'label' => '(GMT+7:00) Vietnam'],
        ['timezone' => 'Asia/Jakarta', 'label' => '(GMT+7:00) Jakarta'],
        ['timezone' => 'Asia/Irkutsk', 'label' => '(GMT+8:00) Irkutsk, Ulaanbaatar'],
        ['timezone' => 'Asia/Shanghai', 'label' => '(GMT+8:00) Beijing, Shanghai'],
        ['timezone' => 'Asia/Hong_Kong', 'label' => '(GMT+8:00) Hong Kong SAR'],
        ['timezone' => 'Asia/Taipei', 'label' => '(GMT+8:00) Taipei'],
        ['timezone' => 'Asia/Kuala_Lumpur', 'label' => '(GMT+8:00) Kuala Lumpur'],
        ['timezone' => 'Asia/Singapore', 'label' => '(GMT+8:00) Singapore'],
        ['timezone' => 'Australia/Perth', 'label' => '(GMT+8:00) Perth'],
        ['timezone' => 'Asia/Yakutsk', 'label' => '(GMT+9:00) Yakutsk'],
        ['timezone' => 'Asia/Seoul', 'label' => '(GMT+9:00) Seoul'],
        ['timezone' => 'Asia/Tokyo', 'label' => '(GMT+9:00) Osaka, Sapporo, Tokyo'],
        ['timezone' => 'Australia/Darwin', 'label' => '(GMT+9:30) Darwin'],
        ['timezone' => 'Australia/Adelaide', 'label' => '(GMT+9:30) Adelaide'],
        ['timezone' => 'Asia/Vladivostok', 'label' => '(GMT+10:00) Vladivostok'],
        ['timezone' => 'Pacific/Port_Moresby', 'label' => '(GMT+10:00) Guam, Port Moresby'],
        ['timezone' => 'Australia/Brisbane', 'label' => '(GMT+10:00) Brisbane'],
        ['timezone' => 'Australia/Sydney', 'label' => '(GMT+10:00) Canberra, Melbourne, Sydney'],
        ['timezone' => 'Australia/Hobart', 'label' => '(GMT+10:00) Hobart'],
        ['timezone' => 'Asia/Magadan', 'label' => '(GMT+11:00) Magadan'],
        ['timezone' => 'SST', 'label' => '(GMT+11:00) Solomon Islands'],
        ['timezone' => 'Pacific/Noumea', 'label' => '(GMT+11:00) New Caledonia'],
        ['timezone' => 'Asia/Kamchatka', 'label' => '(GMT+12:00) Kamchatka'],
        ['timezone' => 'Pacific/Fiji', 'label' => '(GMT+12:00) Fiji Islands, Marshall Islands'],
        ['timezone' => 'Pacific/Auckland', 'label' => '(GMT+12:00) Auckland, Wellington'],
        ['timezone' => 'Pacific/Apia', 'label' => '(GMT+13:00) Independent State of Samoa'],
    ];
}
