<?php

namespace App\Helpers\Interfaces;

interface UniversityEventTypes
{
    const UNIVERSITY_EVENT_TYPE_OPENDAY = 1; //TODO: UPDATE THE ID FOR UNIVERSITY_EVENT_TYPE table
    const UNIVERSITY_EVENT_TYPE_WORKSHOP = 2; //TODO: UPDATE THE ID FOR UNIVERSITY_EVENT_TYPE_event_types table
    const UNIVERSITY_EVENT_TYPE_COMPITITION = 4; //TODO: UPDATE THE ID FOR UNIVERSITY_EVENT_TYPE_event_types table
    const UNIVERSITY_EVENT_TYPE_STUDENT_FOR_DAY = 3; //TODO: UPDATE THE ID FOR UNIVERSITY_EVENT_TYPE_event_types table

}
